#!/usr/bin/env ts-node
/**
 * AI Automation Framework — Setup CLI
 *
 * Run once to configure your environment:
 *   npx ts-node src/setup.ts
 *
 * What it does:
 *   1. Asks for your app URL, username, password
 *   2. Generates .env from .env.example
 *   3. Installs Playwright browsers
 *   4. Creates required output directories
 *   5. Validates the setup with a quick connectivity check
 */

import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";
import { execSync } from "child_process";

const ROOT = path.resolve(__dirname, "..");
const ENV_FILE = path.join(ROOT, ".env");
const ENV_EXAMPLE = path.join(ROOT, ".env.example");

const REQUIRED_DIRS = [
  "test-results/screenshots",
  "test-results/downloads",
  "test-results/diffs",
  "test-results/logs",
  "test-results/traces",
  "test-results/sessions",
  "test-results/visual-baselines",
];

function ask(rl: readline.Interface, question: string, defaultVal = ""): Promise<string> {
  return new Promise(resolve => {
    const prompt = defaultVal ? `${question} [${defaultVal}]: ` : `${question}: `;
    rl.question(prompt, answer => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

function print(msg: string) { console.log(msg); }
function ok(msg: string)    { console.log(`  ✅ ${msg}`); }
function warn(msg: string)  { console.log(`  ⚠️  ${msg}`); }
function step(msg: string)  { console.log(`\n▶ ${msg}`); }

/** Strip characters that could inject new lines or env var keys into .env */
function sanitizeEnvValue(val: string): string {
  return val.replace(/[\r\n]/g, "").replace(/["'`\\]/g, "");
}

async function main() {
  print("\n╔══════════════════════════════════════════════════╗");
  print("║     AI Automation Framework — Setup Wizard       ║");
  print("╚══════════════════════════════════════════════════╝\n");

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  // ── Step 1: Collect config ─────────────────────────────────────────────────
  step("Application Configuration");

  const appUrl      = sanitizeEnvValue(await ask(rl, "App URL (login page)", "https://your-app.example.com/login"));
  const baseUrl     = sanitizeEnvValue(await ask(rl, "Base URL (domain only)", appUrl.replace(/\/[^/]*$/, "")));
  const username    = sanitizeEnvValue(await ask(rl, "Test username", ""));
  const password    = sanitizeEnvValue(await ask(rl, "Test password", ""));
  const headless    = sanitizeEnvValue(await ask(rl, "Run headless? (true/false)", "true"));
  const logLevel    = sanitizeEnvValue(await ask(rl, "Log level (debug/info/warn/error)", "info"));
  const learning    = sanitizeEnvValue(await ask(rl, "Enable self-healing learning? (true/false)", "true"));

  rl.close();

  // ── Step 2: Generate .env ──────────────────────────────────────────────────
  step("Generating .env");

  if (!fs.existsSync(ENV_EXAMPLE)) {
    warn(".env.example not found — creating .env from scratch");
  }

  const envContent = `# Generated by setup.ts on ${new Date().toISOString()}
# Edit manually or re-run: npx ts-node src/setup.ts

# ── Application ───────────────────────────────────────────────────────────────
APP_URL=${appUrl}
APP_USERNAME=${username}
APP_PASSWORD=${password}

# ── Browser ────────────────────────────────────────────────────────────────────
BASE_URL=${baseUrl}
HEADLESS=${headless}

# ── CI ─────────────────────────────────────────────────────────────────────────
CI=false

# ── Framework timeouts (milliseconds) ─────────────────────────────────────────
FW_TIMEOUT=5000
FW_WAIT_TIMEOUT=5000
FW_STRATEGY_TIMEOUT=1000
FW_MAX_BACKOFF_MS=2000
FW_IFRAME_TIMEOUT=10000
FW_SLOW_TYPE_MS=80

# ── Framework retries ──────────────────────────────────────────────────────────
FW_MAX_RETRIES=3
FW_BACKOFF=true

# ── Framework learning ─────────────────────────────────────────────────────────
FW_LEARNING=${learning}
FW_DB_PATH=learning-db.json

# ── Framework logging ──────────────────────────────────────────────────────────
FW_LOG_LEVEL=${logLevel}

# ── Output directories ─────────────────────────────────────────────────────────
FW_SCREENSHOT_DIR=test-results/screenshots
FW_DOWNLOAD_DIR=test-results/downloads
FW_DIFF_DIR=test-results/diffs
FW_LOG_DIR=test-results/logs
`;

  const envExists = fs.existsSync(ENV_FILE);
  if (envExists) {
    warn(".env already exists — overwriting");
  }
  fs.writeFileSync(ENV_FILE, envContent, "utf8");
  ok(".env generated");

  // ── Step 3: Create output directories ─────────────────────────────────────
  step("Creating output directories");
  for (const dir of REQUIRED_DIRS) {
    const full = path.join(ROOT, dir);
    fs.mkdirSync(full, { recursive: true });
    ok(dir);
  }

  // ── Step 4: Install Playwright browsers ───────────────────────────────────
  step("Installing Playwright browsers (chromium, firefox, webkit)");
  try {
    execSync("npx playwright install chromium firefox webkit", {
      stdio: "inherit",
      cwd: ROOT
    });
    ok("Browsers installed");
  } catch {
    warn("Browser install failed — run manually: npx playwright install");
  }

  // ── Step 5: Validate TypeScript compiles ──────────────────────────────────
  step("Validating TypeScript compilation");
  try {
    execSync("npx tsc --noEmit", { stdio: "pipe", cwd: ROOT });
    ok("TypeScript compiles cleanly");
  } catch (e) {
    const out = (e as { stdout?: Buffer }).stdout?.toString() ?? "";
    warn(`TypeScript errors found:\n${out.slice(0, 500)}`);
  }

  // ── Done ──────────────────────────────────────────────────────────────────
  print("\n╔══════════════════════════════════════════════════╗");
  print("║              Setup Complete ✅                    ║");
  print("╚══════════════════════════════════════════════════╝");
  print("\nNext steps:");
  print("  npm test                    — run all tests");
  print("  npm run test:smoke          — run smoke suite");
  print("  npm run test:headed         — run with browser visible");
  print("  npm run test:debug          — run with Playwright inspector");
  print("  npm run report              — open HTML report");
  print("  npx playwright show-trace <path>  — debug a failed test\n");
}

main().catch(e => {
  console.error("Setup failed:", e);
  process.exit(1);
});
